os:
  - linux
  - osx

osx_image: xcode11.3

language: cpp

git:
  depth: 1

script: 
  - if [ "$TRAVIS_JOB_NAME" = "32" ] ; then sudo apt-get install gcc-multilib g++-multilib ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew install bison && export PATH="/usr/local/opt/bison/bin:$PATH" && bison --version ; fi
  - export DEBUG=""
  - if [ -f .version ]; then BUILD_VERSION_NUMBER=$(cat .version); else BUILD_VERSION_NUMBER=$TRAVIS_TAG; fi
  - make
  - ./test.sh

jobs:
  include:
    if: os = linux
    name: "32"
    env: BUILD_ADDITIONAL_ARG=-m32

before_deploy:
  - zip lslint_${TRAVIS_TAG}_${TRAVIS_OS_NAME}${TRAVIS_JOB_NAME}.zip lslint

deploy:
  provider: releases
  api_key:
      secure: "jQKKVzbzjVGxJMIZLciXG5r9TtCL9QBOzqPXeGWuNyknLB2kcrhv9PM6qejUiDGOuHHc6NR28N04gvFkAu5gIPIbnpfIIB4LdfgM/BGA52Ichi9hCgrdKiUFZzstRgX62Tfo9MujNz8UPmHnTSG3wFMR/yzO63u+EjIlgh4qQRoqDN7RNoQVgBosuBwjz4Mlt1ACVznyv0emkgfvHnlryL/02hJSqi7OQisn/0z/jY39oof5QaWoKTgT5VeHuVbuEqH1O4UYQBbb6zFJhPBHixkf0j3t/qKqbbCo/Y5o89OcW7WhFChSj8dGjRas+fGHFZH4vHN9bFzqTNkkJOjNmLWFocrDG0azzd5jxnGmrSP3G2EY2G+9nA8ID0awIRT8DVNPuPmtjF1DM10EGNDedsWTa3PDIsJ9so49qq/xO5pJjYpyXhAOE57WMnq55ku/pvhARM7lg4NuE8ivOkYpfZfb6a5s4ym6EGbbEX6dfMT2SFR4nNvSAycBSWbEjC3QrHl3SwlHjzz6tv/Jin9mhIA2ntEiePqCSLMsI/YXfe28K2LuhzDGIpGFtR1eJZytdEZJ6d80h7JOC2CWEglFzCXaPRjtNHH0q1Z28sIVhW9toqKCceYwV+CYPNknRmYfrHTR33zI/qdRMAGuHSlBGiYIECIK+DhPNpO5xnm8XeI="
  file: "lslint_${TRAVIS_TAG}_${TRAVIS_OS_NAME}${TRAVIS_JOB_NAME}.zip"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
